# Generated by Django 4.2 on 2023-05-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=50)),
                ('good_img', models.ImageField(null=True, upload_to='good_img/', verbose_name='positive_cloud')),
                ('bad_img', models.ImageField(null=True, upload_to='bad_img/', verbose_name='negative_cloud')),
                ('poster_img', models.ImageField(upload_to='movie_poster/', verbose_name='poster')),
            ],
        ),
    ]
