# Generated by Django 4.2 on 2023-05-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image2',
            field=models.ImageField(blank=True, upload_to='album_pics'),
        ),
        migrations.AlterField(
            model_name='album',
            name='image3',
            field=models.ImageField(blank=True, upload_to='album_pics'),
        ),
    ]
