# Generated by Django 4.2 on 2023-05-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_alter_album_image2_alter_album_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='votes_n',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
