# Generated by Django 4.2 on 2023-05-03 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album', '0004_album_votes_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='voters',
            field=models.ManyToManyField(related_name='liked_albums', to=settings.AUTH_USER_MODEL),
        ),
    ]
