# Generated by Django 4.2 on 2023-05-04 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_alter_album_image2_alter_album_image3_comment'),
        ('album', '0005_album_voters'),
    ]

    operations = [
    ]
