# Generated by Django 4.2 on 2023-05-04 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0007_rename_votes_n_album_nagative_votes_n_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='nagative_votes_n',
            new_name='negative_votes_n',
        ),
    ]
